---
components:
  schemas: {}
  messages:
    Production Line Started:
      x-ep-event-id: "e8zz7km4saq"
      x-ep-event-version-displayname: "0.1.0"
      x-ep-event-version-id: "76fc3io4iwa"
      x-ep-event-version: "0.1.0"
      x-ep-event-name: "Production Line Started"
      description: "* MES system publishes \"Production line started\" event when\
        \ a production line is started.\n* HMI system subscribes to \"Production line\
        \ started\" event to monitor production status and progress."
      x-ep-event-state-id: "1"
      x-ep-event-state-name: "DRAFT"
    Production Line Stopped:
      x-ep-event-id: "s9sruwpdlxs"
      x-ep-event-version-displayname: "0.1.0"
      x-ep-event-version-id: "1u89eufvvqg"
      x-ep-event-version: "0.1.0"
      x-ep-event-name: "Production Line Stopped"
      description: "* MES system publishes \"Production line stopped\" event when\
        \ a production line is stopped.\n* HMI system subscribes to \"Production line\
        \ stopped\" event to monitor production status and performance."
      x-ep-event-state-id: "1"
      x-ep-event-state-name: "DRAFT"
channels:
  acmeManufacturing/sc/productionLine/{productID}/started/v1/mes/{productionLineID}:
    subscribe:
      message:
        $ref: "#/components/messages/Production Line Started"
    publish:
      message:
        $ref: "#/components/messages/Production Line Started"
    parameters:
      productID:
        schema:
          type: "string"
        x-ep-parameter-name: "productID"
      productionLineID:
        schema:
          type: "string"
        x-ep-parameter-name: "productionLineID"
  acmeManufacturing/sc/productionLine/{productID}/stopped/v1/mes/{productionLineID}:
    subscribe:
      message:
        $ref: "#/components/messages/Production Line Stopped"
    publish:
      message:
        $ref: "#/components/messages/Production Line Stopped"
    parameters:
      productID:
        schema:
          type: "string"
        x-ep-parameter-name: "productID"
      productionLineID:
        schema:
          type: "string"
        x-ep-parameter-name: "productionLineID"
asyncapi: "2.5.0"
info:
  x-ep-event-api-version: "0.1.0"
  x-ep-event-api-id: "x4dbcrlo5os"
  description: "This Event API involves the MES system to start and stop production\
    \ lines, and the human machine interface (HMI) system to monitor production status\
    \ and progress.\n\n* MES system publishes \"Production line started\" event when\
    \ a production line is started.\n* HMI system subscribes to \"Production line\
    \ started\" event to monitor production status and progress.\n* MES system publishes\
    \ \"Production line stopped\" event when a production line is stopped.\n* HMI\
    \ system subscribes to \"Production line stopped\" event to monitor production\
    \ status and performance."
  x-ep-displayname: "0.1.0"
  x-ep-state-name: "DRAFT"
  title: "Production Scheduling and Monitoring Event API"
  x-ep-application-domain-id: "06jf5fwrcrf"
  version: "0.1.0"
  x-ep-state-id: "1"
  x-ep-event-api-version-id: "ckgwk4f1u6r"
  x-ep-application-domain-name: "Acme Manufacturing - Supply Chain Optimisation"
